// Mocks generated by Mockito 5.4.2 from annotations
// in vesser/test/features/start/data/repositories/internet_checker_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:vesser/src/features/start/data/services/check_internet_connection_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CheckInternetConnectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckInternetConnectionService<T> extends _i1.Mock
    implements _i3.CheckInternetConnectionService<T> {
  @override
  _i2.Future<T> get currentConnectionStatus => (super.noSuchMethod(
        Invocation.getter(#currentConnectionStatus),
        returnValue: _i4.ifNotNull(
              _i4.dummyValueOrNull<T>(
                this,
                Invocation.getter(#currentConnectionStatus),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_0<T>(
              this,
              Invocation.getter(#currentConnectionStatus),
            ),
        returnValueForMissingStub: _i4.ifNotNull(
              _i4.dummyValueOrNull<T>(
                this,
                Invocation.getter(#currentConnectionStatus),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_0<T>(
              this,
              Invocation.getter(#currentConnectionStatus),
            ),
      ) as _i2.Future<T>);
  @override
  _i2.Stream<T> get internetConnectionChanges => (super.noSuchMethod(
        Invocation.getter(#internetConnectionChanges),
        returnValue: _i2.Stream<T>.empty(),
        returnValueForMissingStub: _i2.Stream<T>.empty(),
      ) as _i2.Stream<T>);
}
